// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Jul 11 14:54:03 2024

freq_sm freq_sm_inst
(
	.en(en_sig) ,	// input  en_sig
	.clk(clk_sig) ,	// input  clk_sig
	.step_size(step_size_sig) ,	// input  step_size_sig
	.dir(dir_sig) ,	// input  dir_sig
	.on_switch(on_switch_sig) ,	// input  on_switch_sig
	.quarter(quarter_sig) ,	// input  quarter_sig
	.resetb(resetb_sig) ,	// input  resetb_sig
	.motor(motor_sig) ,	// output [3:0] motor_sig
	.en_counter_check(en_counter_check_sig) ,	// output  en_counter_check_sig
	.enable_check(enable_check_sig) ,	// output  enable_check_sig
	.prev_enable_check(prev_enable_check_sig) ,	// output  prev_enable_check_sig
	.counter_check(counter_check_sig) ,	// output [6:0] counter_check_sig
	.count_ended_check(count_ended_check_sig) 	// output  count_ended_check_sig
);

defparam freq_sm_inst.first = 'b0001;
defparam freq_sm_inst.second = 'b0011;
defparam freq_sm_inst.third = 'b0010;
defparam freq_sm_inst.fourth = 'b0110;
defparam freq_sm_inst.fifth = 'b0100;
defparam freq_sm_inst.sixth = 'b1100;
defparam freq_sm_inst.seventh = 'b1000;
defparam freq_sm_inst.eighth = 'b1001;
